<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1>Demo Google Authenticator!</h1>
        <p>This is an example of how use the Google Authenticator in your website with the leandrolugaresi/google-authenticator repository. This example code and the repository used are in the GitHub.</p>
        <p>
            <a href="https://github.com/leandro-lugaresi/google-authenticator" class="btn btn-primary btn-lg" role="button">Go to repository</a>
            <a href="https://github.com/leandro-lugaresi/google-authenticator-exemple" class="btn btn-default btn-lg" role="button">Go to source code</a>
        </p>
    </div>
</div>
