<div class="container">
    <h1>Create an User</h1>
</div>
<div class="container">
    <div class="">
        <form role="form" action="" method="POST">
            <div class="form-group">
                <label for="exampleName">name</label>
                <input type="text" name="name" class="form-control" id="exampleName" placeholder="Enter name">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>

</div> <!-- /container -->
