<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Leandro Lugaresi">
        <link rel="icon" href="/img/favicon.ico">

        <title>Google Authenticator example</title>

        <!-- Bootstrap core CSS -->
        <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="/bootstrap/css/jumbotron.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Demostration</a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php if (!isset($_SESSION['isAuth']) || $_SESSION['isAuth'] === false): ?>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/user/login">Sign in</a></li>
                        <li><a href="/user/create">New user</a></li>
                    </ul>

                    <?php else: ?>
                    <ul class="nav navbar-nav">
                        <li><a href="/user">Users</a></li>
                        <li><a href="/user/create">New user</a></li>
                        <li><a href="/user/activate">Activate Google Authenticator</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged as: <?php echo $_SESSION['auth']; ?> <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="/user/logout">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                    <?php endif ?>
                </div>
            </div>
        </div>

        <?php echo $this->content(); ?>

        <hr>
        <div class="container">
            <footer>
                <p>Template by <a href="http://getbootstrap.com/">Bootstrap</a></p>
            </footer>
        </div>
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="/bootstrap/js/bootstrap.min.js"></script>
    </body>
</html>
